service: block-ql
provider:
  name: aws
  runtime: nodejs10.x
  environment:
    STRIPE_SECRET_KEY: sk_live_K2UrxLoW0B37q4VJyXvZiao8
    STRIPE_SUCCESS_URL: https://hodlstream.com/success
    STRIPE_CANCEL_URL: https://hodlstream.com/shop
    SERVER_URI: https://laqr73ujn2.execute-api.us-east-1.amazonaws.com/dev
    FROM: HODL Stream <rphansen91@gmail.com>
    RECIPIENTS: rphansen91@gmail.com
    ARTICLES_KEY: articles
    RESOURCE_BUCKET: hodlstream-resources

functions:
  graphQl:
    handler: lambda.graphql
    events:
      - http:
          path: graphql
          method: post
          cors: true
  fbVerify:
    handler: lambda.fbverify
    events:
      - http:
          path: facebook
          method: get
          cors: true
  fbWebhook:
    handler: lambda.fbwebhook
    events:
      - http:
          path: facebook
          method: post
          cors: true
  cacheNews:
    handler: lambda.cacheNews
    events:
      - http:
          path: cacheNews
          method: get
      - schedule: rate(1 day)
  activateArticle:
    handler: lambda.activateArticle
    events:
      - http:
          path: articles/activate/{id}
          method: get
          request: 
            parameters: 
              paths: 
                id: true
  deactivateArticle:
    handler: lambda.deactivateArticle
    events:
      - http:
          path: articles/deactivate/{id}
          method: get
          request: 
            parameters: 
              paths: 
                id: true
  postArticle:
    handler: lambda.postArticle
    events:
      - http:
          path: articles/post/{id}
          method: get
          request: 
            parameters: 
              paths: 
                id: true
